### ISSUE TITLE
Empty item in dropdown not visible

### ISSUE THREAD

**Issue by tofulm** [iendeavor/vue-next-select#125]
Il we have an empty item in dropdown, it's no visible.
![emtpy_item_not_visible](https://user-images.githubusercontent.com/2989137/111753412-20ffb400-8897-11eb-80af-a16486b00a01.png)
With 
```css
.vue-dropdown-item > span {
    display : inline-block;
    min-height: 1rem;
}
```
It's OK
![emtpy_item_visible](https://user-images.githubusercontent.com/2989137/111753626-6328f580-8897-11eb-8846-6d669ff66576.png)
